### ISSUE TITLE
解码测试图片

### ISSUE THREAD

**Issue by nuintun** [nuintun/qrcode#3]
![qrcode](https://user-images.githubusercontent.com/1730277/57219316-46c89a80-702a-11e9-87da-7f43e9e905c5.jpg)

![qrcode](https://user-images.githubusercontent.com/1730277/57219329-4defa880-702a-11e9-8b4a-efb535a44ce0.jpg)

![input](https://user-images.githubusercontent.com/1730277/57219345-5a740100-702a-11e9-940d-d5d8577bb940.png)

**Comment by shoyuf** [comment]
![qrcode_github com](https://user-images.githubusercontent.com/27998490/167333029-ce00cde8-65b9-4c24-a7bd-cfd4c9ab3375.png)
无法支持chrome生成的二维码吗？

**Comment by nuintun** [comment]
@shoyuf 暂不支持，上游 jsQR 异形二维码支持并不完善，后面有时间把 zxing 的 finder 拿来试试。
