### ISSUE TITLE
Version 4.0.0 ?

### ISSUE THREAD

**Issue by lollita** [nuintun/qrcode#317]
I don't know why, I have a [4.0.0. version file](http://midiquiz.altervista.org/temp/qrcode_4.0.js).
Can you explain to me that?

**Comment by nuintun** [comment]
Strange, I didn't release 4.0.0 😮

**Comment by nuintun** [comment]
Notes: Th version information is provided by `package.json`.

https://github.com/nuintun/qrcode/blob/643513cced42c408c598ec5d93ada417f7ac3131/tools/rollup.base.js#L5-L18

**Comment by TechQuery** [comment]
The real change log of version 4.0.0 is here: https://github.com/nuintun/qrcode/compare/d580ef1c601d0437bf2c995a573b778fda353b57...7560648fdd70f0be6166e4110d802a7441b50add
