### ISSUE TITLE
Provide scalable image format

### ISSUE THREAD

**Issue by FantasqueX** [nuintun/qrcode#319]
Hi, I have a question about how to fit the generated qrcode into my HTML. Currently, the generated qrcode is a GIF image which is not scalable. And I don't know how to set moduleSize to fit the desired size. So, could you please provide an option to export SVG or to draw a Canvas automatically?

**Comment by nuintun** [comment]
Use `toDataURL(moduleSize?: number, margin?: number): string` scale image.

Image size = (version * 4 + 17) * moduleSize + margin * 2

Also you can use `getMatrix` get qrcode matrix and draw svg by youself!
