### ISSUE TITLE
请教一下应该如何配置可以设置二维码的清晰度

### ISSUE THREAD

**Issue by Jimmylxue** [nuintun/qrcode#330]
现在默认导出来的二维码很小 做一些放大处理的时候很不清晰 请教一下应该如何配置呢

**Comment by nuintun** [comment]
```ts
toDataURL(moduleSize?: number, margin?: number): string
```

`moduleSize` 设置二维码单个块的像素大小

`margin` 设置二维码四周静区大小，推荐四倍 `moduleSize`

`v3`版生成`gif`字典的代码有性能问题，高版本二维码不推荐设置过大！`v4`版（暂未发布）性能优化，可以设置大些，后面`v3`版会同步部分`v4`版优化！

`v4`版示例 https://nuintun.github.io/qrcode/packages/examples/static/index.html#/encode

**Comment by nuintun** [comment]
`v3` 新版已发布~
