### ISSUE TITLE
Failed to decode QR code.

### ISSUE THREAD

**Issue by yapzhenyie** [nuintun/qrcode#334]
I'm facing one issue where the qrcode library not able to decode the below qrcode image.

I tried decode in some other websites or even using my phone qr code scanner. It was able to decode, but @nuintun/qrcode library not.
![WhatsApp Image 2024-04-27 at 23 45 29](https://github.com/nuintun/qrcode/assets/13622737/1fbca97f-2fee-4110-b88d-9387d5d55408)

**Comment by nuintun** [comment]
The QR code decoding does not perform extensive image preprocessing for performance considerations.

The example image you provided has too high a resolution, resulting in imperfections in the image after binarization.

![image](https://github.com/nuintun/qrcode/assets/1730277/b5dfa235-2069-4829-bf07-919672b1e98d)

You can try resizing the image to an appropriate size before decoding.

![20240508161244](https://github.com/nuintun/qrcode/assets/1730277/09ab66fa-e8ac-4feb-9823-597d796c96b0)

![image](https://github.com/nuintun/qrcode/assets/1730277/8aaff8f8-2ec8-4bee-9664-e51e88935580)
