### ISSUE TITLE
fail to decode image

### ISSUE THREAD

**Issue by wzhsh90** [nuintun/qrcode#335]
![2](https://github.com/user-attachments/assets/37d71b4f-00ba-41ca-a15c-148139e12178)

**Comment by nuintun** [comment]
Your image has defects after binarization. You just need to scale the image to an appropriate size; no binarization algorithm can suit all situations!


![下载 (1)](https://github.com/user-attachments/assets/e919f5cb-74fa-4010-8c4c-1c20f5a84b04)

![企业微信截图_20240826092915](https://github.com/user-attachments/assets/f365e6a8-0d4a-48a0-aeb5-3fee3471ec56)

![image](https://github.com/user-attachments/assets/67efd4c4-afa3-4e93-8563-5c51fc04e1bb)

Duplicate: https://github.com/nuintun/qrcode/issues/334
